SELECT F.FLAVOR 
FROM FIRST_HALF F JOIN
(SELECT FLAVOR, SUM(TOTAL_ORDER) AS 'SUM_ORDER' FROM JULY GROUP BY FLAVOR) J
ON F.FLAVOR = J.FLAVOR
GROUP BY FLAVOR
ORDER BY F.TOTAL_ORDER + J.SUM_ORDER DESC
LIMIT 3;