SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME,
    SUBSTR(BOOK.PUBLISHED_DATE,1,10) AS 'PUBLISHED_DATE'
    FROM BOOK JOIN AUTHOR
    ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
    WHERE BOOK.CATEGORY LIKE '경제'
    ORDER BY PUBLISHED_DATE ASC;